# Generated by Django 5.2.13 on 2026-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_request_author_alter_vote_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
