# Generated by Django 6.0.5 on 2026-05-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_request_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
