# Generated by Django 6.0.5 on 2026-05-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_citizenprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='deleted_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
