# Generated by Django 6.0.5 on 2026-05-09 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_request_deleted_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='deleted_by_admin',
        ),
    ]
