# Generated by Django 6.0.5 on 2026-05-10 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_request_deleted_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('vote', 'На голосуванні'), ('review', 'На розгляді'), ('approved', 'Виділено кошти'), ('implemented', 'Реалізовано')], default='vote', max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_set', to='requests_app.request'),
        ),
    ]
