# Generated by Django 6.0.5 on 2026-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_request_status_alter_vote_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
